### ISSUE TITLE
Passing in a custom mapping through .msg

### ISSUE THREAD

**Issue by scottsweb** [borjiso/node-red-contrib-scrape-it#1]
Hi, I am looking at using your node (thanks for making it) and have been looking at options for passing in a custom mapping through the `.msg` property. It looks like you currently support that via `msg.payload.mapping`:

https://github.com/borjiso/node-red-contrib-scrape-it/blob/master/scrape-it.js#L12

The issue with that is that payload is most often used to carry the HTML payload, so setting the mapping property under payload is not working for me.

Would you accept a PR to move it up to `msg.mapping` instead?

**Comment by borjiso** [comment]
Hi.
I have merged yours changes.

Thanks for contributing.
