### ISSUE TITLE
scraping input name

### ISSUE THREAD

**Issue by ThibautRuy** [borjiso/node-red-contrib-scrape-it#5]
Hi, 

I am trying to scrape a hidden field in a form 

<input type="hidden" id="token" name="name_token]" value="123435">

But I cannot manage to define the appropriate selector for that. I tried : 
```
{
    "token": "input[name~='[name_token]']"
}
```

Is it a limitation or a do I wrong write my selector ?

**Comment by borjiso** [comment]
Do you check the reference on https://github.com/IonicaBizau/scrape-it ?
